### ISSUE TITLE
Unexpected error during set up

### ISSUE THREAD

**Issue by Fabsgreg** [laurent-martin/hass_int_toutsurmoneau#1]
Hello, I have the error "Unexpected error" during the integration set up.

Here is the associated log file:

```
Logger: custom_components.portail_eau_fr.config_flow
Source: custom_components/portail_eau_fr/config_flow.py:52 
Integration: Tout sur mon eau ([documentation](https://github.com/laurent-martin/hass_int_toutsurmoneau)) 
First occurred: 12:15:10 AM (3 occurrences) 
Last logged: 12:21:36 AM

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/portail_eau_fr/config_flow.py", line 52, in async_step_user
    "default_meter_id": await client.async_meter_id(),
  File "/usr/local/lib/python3.10/site-packages/toutsurmoneau/async_client.py", line 168, in async_meter_id
    self._id = await self._async_find_in_page(
  File "/usr/local/lib/python3.10/site-packages/toutsurmoneau/async_client.py", line 96, in _async_find_in_page
    raise ClientError(f"Could not find {reg_ex} in {page}")
toutsurmoneau.errors.ClientError: Could not find /month/([0-9]+) in historique-de-consommation-tr
```

Feel free to ask me if you need more information/logs.
Thanks for all your hard work on this integration.

**Comment by oasisck** [comment]
Hi there, I have exactly the same error at the moment
it seems an issue about a regex

**Comment by laurent-martin** [comment]
The config flow tries to get the default meter id , but apparently it fails.

I'll push a new version that ignores the error, but then the user has to manually input the meter id found in that page.

If you want, send me by email the content of page:
https://www.toutsurmoneau.fr/mon-compte-en-ligne/historique-de-consommation-tr

So, I can see why the pasing does not get the meter id from there....

**Comment by laurent-martin** [comment]
Version 0.0.2 should fix this.

There is a github release so HACS should propose the upgrade.

**Comment by Fabsgreg** [comment]
Thanks, package updated but I now have another error:

```
Logger: custom_components.portail_eau_fr.config_flow
Source: custom_components/portail_eau_fr/config_flow.py:59 
Integration: Tout sur mon eau ([documentation](https://github.com/laurent-martin/hass_int_toutsurmoneau)) 
First occurred: 2:52:11 PM (4 occurrences) 
Last logged: 3:03:18 PM

An exception ocurred
Traceback (most recent call last):
  File "/config/custom_components/portail_eau_fr/config_flow.py", line 59, in async_step_user
    "contract": (await client.async_contracts())[0],
  File "/usr/local/lib/python3.10/site-packages/toutsurmoneau/async_client.py", line 177, in async_contracts
    contract_list = await self._async_call_api(API_ENDPOINT_CONTRACT)
  File "/usr/local/lib/python3.10/site-packages/toutsurmoneau/async_client.py", line 142, in _async_call_api
    await self._async_ensure_logged_in()
  File "/usr/local/lib/python3.10/site-packages/toutsurmoneau/async_client.py", line 130, in _async_ensure_logged_in
    raise ClientError(
toutsurmoneau.errors.ClientError: Login error: no tableau-de-bord found in je-me-connecte.
```

My water provider is Eau du bas Languedoc which belongs to Suez, to follow my water consumption I go to this [link](https://eaudubaslanguedoc.toutsurmoneau.fr/mon-compte-en-ligne/historique-de-consommation-tr)
Could there be a correlation with my error?

For information, I tried to change the url during the set up with this one: [https://eaudubaslanguedoc.toutsurmoneau.fr/mon-compte-en-ligne/tableau-de-bord](https://eaudubaslanguedoc.toutsurmoneau.fr/mon-compte-en-ligne/tableau-de-bord), same error

**Comment by laurent-martin** [comment]
For the URL did you provide:

https://eaudubaslanguedoc.toutsurmoneau.fr/mon-compte-en-ligne

**Comment by Fabsgreg** [comment]
I had put the wrong url when I first tried... 
This time, the installation succeeded and in the next step I was able to fill-in my water meter id (recovered by inspecting the source code) but now the error "Failed to set up" appears on my integration.
I checked the logs but I can't find anything related
<img width="294" alt="Screenshot 2023-03-20 at 15 35 22" src="https://user-images.githubusercontent.com/17829244/226374847-bcb4cbe8-19d3-468c-81d2-1fba58962432.png">

**Comment by laurent-martin** [comment]
it's possible to enable logs using the menu:
![image](https://user-images.githubusercontent.com/11157566/226437927-46a5f49e-1a3e-46f4-907e-a4331e81f677.png)

**Comment by Fabsgreg** [comment]
I activated the logs and reloaded the integration, but still nothing

1/
<img width="285" alt="Screenshot 2023-03-20 at 20 03 46" src="https://user-images.githubusercontent.com/17829244/226441079-2a614089-2efd-4d13-9d68-1ec96e181547.png">

2/
<img width="289" alt="Screenshot 2023-03-20 at 20 04 36" src="https://user-images.githubusercontent.com/17829244/226441158-4b088eaf-a785-47ab-b592-2d47edf86b6d.png">

3/ Then clicked on "Check the logs"
<img width="1173" alt="Screenshot 2023-03-20 at 20 05 17" src="https://user-images.githubusercontent.com/17829244/226441233-4dfd89f4-3903-40d4-b75d-68f90a1fb52e.png">

Same result by removing portail_eau_fr from the Search bar

**Comment by laurent-martin** [comment]
Add this to configuration.yaml:

```yaml
logger:
  default: info
  logs:
    toutsurmoneau: debug
    custom_components.portail_eau_fr: debug
```

**Comment by Fabsgreg** [comment]
Done but still nothing, I can see logs of other components but nothing about portail_eau_fr

**Comment by Fabsgreg** [comment]
Finally found something by loading full logs:

```
2023-03-20 20:18:14.553 INFO (MainThread) [homeassistant.setup] Setting up portail_eau_fr
2023-03-20 20:18:14.554 INFO (MainThread) [homeassistant.setup] Setup of domain portail_eau_fr took 0.0 seconds
2023-03-20 20:19:22.389 DEBUG (MainThread) [custom_components.portail_eau_fr] >>>>>>>>>>> config: {'username': '****', 'password': '****', 'meter_id': '****', 'url': 'https://eaudubaslanguedoc.toutsurmoneau.fr/mon-compte-en-ligne'}
```

**Comment by laurent-martin** [comment]
Hum. That's a little light, it just means that the configuration started and got the values just before testing the credentials.

Did you also activate the log for "toutsurmoneau"

(also released new version)

**Comment by Fabsgreg** [comment]
I tested with the 0.0.3, same result, concerning the logs, I added the configuration given above to my configuration.yaml
Do I need to add anything else to my configuration.yaml?

**Comment by Fabsgreg** [comment]
I may have a clue, I downloaded and run your python package `toutsurmoneau 0.0.18` and everything is working fine, I can connect and collect data.
I then went back to HA and searched for logs and finally found something after removing some filters:
```
2023-03-26 00:29:00.539 DEBUG (MainThread) [custom_components.portail_eau_fr] async_setup_entry: config: {'username': '***', 'password': '***', 'meter_id': '***', 'url': 'https://eaudubaslanguedoc.toutsurmoneau.fr/mon-compte-en-ligne'}
2023-03-26 00:29:00.539 DEBUG (MainThread) [custom_components.portail_eau_fr] Client created. Checking credentials
2023-03-26 00:29:00.540 DEBUG (MainThread) [toutsurmoneau.async_client] Calling: donnees-contrats
2023-03-26 00:29:03.539 DEBUG (MainThread) [toutsurmoneau.async_client] Login failed: Login error: https://www.toutsurmoneau.fr/mon-compte-en-ligne: no tableau-de-bord found in je-me-connecte.
```
It seems that `toutsurmoneau` tries to connect with the default url without taking the one specified during the configuration of the component

**Comment by laurent-martin** [comment]
Good catch, I will investigate in that direction.

**Comment by laurent-martin** [comment]
Version 0.0.4 of integration is released.

**Comment by Fabsgreg** [comment]
All good, everything is working fine now, thanks for the fix
