### ISSUE TITLE
Add SEOP provider

### ISSUE THREAD

**Issue by jordanauge** [laurent-martin/hass_int_toutsurmoneau#10]
Hi,

The plugin is also working fine with the SEOP provider. Thanks for the contribution.
Would it be possible to add it to the list of provider URLs ?

https://www.seop.fr/mon-compte-en-ligne

Thanks

**Comment by laurent-martin** [comment]
Yes, I have added a few providers from google search, but it's in python module:
https://github.com/laurent-martin/py-mon-eau/blob/main/toutsurmoneau/const.py
It will come in a future version of the hacs.

**Comment by jordanauge** [comment]
Thanks, i should have checked before, sorry :) You can close this topic
Very useful work.
