### ISSUE TITLE
Fail to setup new install

### ISSUE THREAD

**Issue by Lap1nator** [laurent-martin/hass_int_toutsurmoneau#11]
Hi Laurent,

Thanks for your amazing work on this.

I just try to install your HACS addon and I'm facing an issue once I try to put my creds on the authentication page:

Traceback (most recent call last):
  File "/config/custom_components/portail_eau_fr/config_flow.py", line 81, in async_step_user
    "contract": (await client.async_contracts())[0],
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/toutsurmoneau/async_client.py", line 198, in async_contracts
    contract_list = await self._async_call_api(API_ENDPOINT_CONTRACT)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/toutsurmoneau/async_client.py", line 168, in _async_call_api
    raise ClientError('Failed refreshing cookie')
toutsurmoneau.errors.ClientError: Failed refreshing cookie

Don't hesitate to ask more details (I'm quite a noob on HA but I'm pretty good student so :) )

We can exchange in french too (si besoins).

Good night

**Comment by laurent-martin** [comment]
oui, des pages ont changé, il va falloir corriger...

**Comment by laurent-martin** [comment]
See if version 0.0.6 fixes that.
It works for me.
one can test with command line:
https://github.com/laurent-martin/py-mon-eau

**Comment by Lap1nator** [comment]
Hi Laurent,

Finally, after uninstalling it and reinstalling it, it works on 0.0.7.

Thanks !

**Comment by laurent-martin** [comment]
Thanks for the feedback.
