### ISSUE TITLE
Connection a Odivea impossible suite à mise a jour vers 0.0.5

### ISSUE THREAD

**Issue by ebezine** [laurent-martin/hass_int_toutsurmoneau#12]
Bonjour et merci pour votre travail sur l'intégration Tout sur mon eau à Home Assistant.

Je suis abonné Odivea (Dijon, https://www.odivea.fr/mon-compte-en-ligne/je-me-connecte) et l'intégration a fonctionné correctement jusqu'à aujourd'hui (la dernière mesure collectée date de ce matin).

J'ai effectué la mise a jour vers la 0.0.5 et j'ai désormais une erreur (a la connexion comme a la création d'un nouvel accès) 

```
File "/usr/local/lib/python3.12/site-packages/toutsurmoneau/async_client.py", line 168, in _async_call_api
    raise ClientError('Failed refreshing cookie')
toutsurmoneau.errors.ClientError: Failed refreshing cookie
```

J'ai tenté un rollback vers la 0.0.4, mais je rencontre le même souci, ce qui semble un peu étonnant: juste avant l'upgrade, le sensor était encore actif.

Merci pour votre aide!

**Comment by laurent-martin** [comment]
Apparemment, suez a fait une mise a jour de leur site, et la version 0.0.4 ne fonctionnait plus.

J'ai mis a jour avec 0.0.5, cela a l'aire de fonctionner pour moi.

la version 0.0.4 pouvait deviner le counter id, mais pas la 0.0.5

essayer de re-creer l'entite, mais il vous faudra le "counter id".

**Comment by laurent-martin** [comment]
Nouvelle version 0.0.6, elle fonctionne pour moi (la detection du numero de compteur ne marche plus, mais on peut l'entrer manuellement)
il est egalement possible de tester le fonctionnement avec la ligne de commande:
https://github.com/laurent-martin/py-mon-eau

**Comment by ebezine** [comment]
Malheureusement, y compris avec la version 0.0.7, je rencontre la même erreur.

J'ai supprimé la configuration existante (via l'interface de gestion des intégrations de Home Assistant), supprimé le composant dans HACS, retéléchargé le composant dans HACS et tenté de recréer une configuration.

Cela échoue en affichant "Unknown Error" dans l'interface.

Le log indique
```
Traceback (most recent call last):
  File "/config/custom_components/portail_eau_fr/config_flow.py", line 81, in async_step_user
    "contract": (await client.async_contracts())[0],
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/toutsurmoneau/async_client.py", line 241, in async_contracts
    contract_list = await self._async_call_api(API_ENDPOINT_CONTRACT)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/toutsurmoneau/async_client.py", line 211, in _async_call_api
    raise ClientError('Failed refreshing cookie')
toutsurmoneau.errors.ClientError: Failed refreshing cookie
```

**Comment by fgrandouiller** [comment]
Bonjour, 
J'avais également un souci depuis un certain temps. Je n'avais pas fait bien attention.
Je viens de réinstaller la version 0.0.12 et tout semble fonctionner. Je n'ai plus l'erreur de configuration.

**Comment by ebezine** [comment]
Pour ma part, la version 0.0.9 a résolu le problème que j'avais. Merci !
