### ISSUE TITLE
"Unexpected Error" lors de la configuration de l'intégration

### ISSUE THREAD

**Issue by lraulet** [laurent-martin/hass_int_toutsurmoneau#14]
Bonjour,
Je tente d'utiliser l'intégration mais sans succès.
Lorsque je rentre mes identifiants (je suis à la seop) j'ai l'erreur "Unexpected Error".
![image](https://github.com/laurent-martin/hass_int_toutsurmoneau/assets/2420500/824adfd2-486a-4c60-92d8-7cc4b1fbf5b1)

A noter que si je mets volontairement un mauvais mot de passe j'ai bien l'erreur "Failed to login. Verify login details are correct." ; j'en déduis que les credentials sont correctes.
Je me demande si l'erreur n'est pas dû au bug que j'ai ouvert dans "py-mon-eau" : https://github.com/laurent-martin/py-mon-eau/issues/1

Voici ma config Homeassistant : 
![image](https://github.com/laurent-martin/hass_int_toutsurmoneau/assets/2420500/bb045991-7f66-4c41-97e5-dbccd30df4a7)

Par avancer, merci.

**Comment by laurent-martin** [comment]
Oui, e effet, si cela ne marche pas sur le module de base, c'erst las cause sur l'integration.

**Comment by lraulet** [comment]
@laurent-martin ,
Je vous confirme que le problème vient en effet des bugs :
https://github.com/laurent-martin/py-mon-eau/issues/1
https://github.com/laurent-martin/py-mon-eau/issues/2
Cette liste n'est peut être pas exhaustive car j'ai mis en place un contournement moche de mon coté pour me débloquer :  
Sur mon installation j'ai modifié la première entrée de la liste KNOWN_PROVIDER_URLS (fichier const.py) afin d'y mettre l'URL de mon provider. Puis j'ai modifié la constate PUBLIC_BASE_URL (fichier async_client.py de la même manière). 
Avec ces modifications je n'ai pas besoin de spécifier mon provider puisqu'il sera celui pris par défaut.

Cela me permet d'avoir l'intégration fonctionnelle mais ne me permet pas de dire si la correction des 2 bugs mentionnés est suffisante pour fixer le support de provider autre que toutsurmoneau.fr

Encore une fois, n'hésitez pas si vous avez besoin d'aide pour valider une nouvelle version. Je le ferai avec plaisir.

**Comment by laurent-martin** [comment]
Bonjour,
Oui j'ai commencé a regarder le week end dernier, je n'ai pas encore commité,
merci pour le retour.

**Comment by laurent-martin** [comment]
J'ai poussé une nouvelle version

**Comment by lraulet** [comment]
Ne manque plus que la dépendance sur py-mon-eau 0.0.25 et on devrait être bon pour l'intégration aussi.

**Comment by lraulet** [comment]
@laurent-martin 
Je viens de voir que vous venez de pousser une nouvelle version 0.0.10 mais elle pointe toujours sur la version py-mon-eau 0.0.24 et non sur la version 0.0.25
https://github.com/laurent-martin/hass_int_toutsurmoneau/blob/main/custom_components/portail_eau_fr/manifest.json

**Comment by laurent-martin** [comment]
Oui, pardon c'est une erreur, c'etait pour tester la mise a jour de la
version de l'integration, mais pas la librairie.

**Comment by lraulet** [comment]
Ok, pas de problème.
Prévenez moi quand vous aurez mis à jour l'intégration avec la mise à jour de la librairie. Je ferai le test.

**Comment by lraulet** [comment]
@laurent-martin 
Je viens de tester la version 0.0.11, pour moi cela me semble OK.
Par contre le numéro du compteur n'a pas été trouvé seul. Je l'ai donc entré à la main.
Maintenant le compteur apparait bien dans l'onglet Energy. Par contre pas de remonté d'info mais ce n'est pas la faute de l'intégration. Depuis le passage d'un technicien je n'ai plus le suivi journalier sur le site web de la Seop. Et en utilisant les APIs les dernières infos remontent au 14 Mars...

Si possible, il serait utile de pouvoir récupérer l'historique de consommation lorsqu'on ajoute l'intégration.
