### ISSUE TITLE
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 369, in _async_configure >  raise UnknownFlow

### ISSUE THREAD

**Issue by NicoDupont** [laurent-martin/hass_int_toutsurmoneau#15]
Bonjour Laurent,

Merci pour cette intégration fort bien utile !

J'ai cette erreur depuis quelques jours. 
L'intégration ne se charge plus.
Je suis allé voir sur le site de suez et j'ai remarqué que j'ai les données à j-2 au lieu de j-1.
Est ce que cela peut expliquer cette erreur ?

Merci

> Logger: homeassistant
> Source: data_entry_flow.py:369
> First occurred: 09:11:28 (1 occurrences)
> Last logged: 09:11:28
> 
> Error doing job: Task exception was never retrieved
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 358, in async_configure
>     result = await self._async_configure(flow_id, user_input)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 369, in _async_configure
>     raise UnknownFlow
> homeassistant.data_entry_flow.UnknownFlow

Core 2024.2.5
Supervisor  2024.03.0
Operating System 11.5
Interface utilisateur 20240207.1

**Comment by laurent-martin** [comment]
L'information de compteur est toujours décalée d'un jour car les données du jour J  ne sont disponibles que le jour J+1, de plus home assistant ne permet pas (facilement) d'inserer des donnees dans la passé.
Pour ma part les versions sont:
 Core 2024.3.1
Supervisor 2024.03.0
Operating System
Interface utilisateur 20240307.0

**Comment by NicoDupont** [comment]
Oui justement avant j'etais a j-1 maintenant c est j-2 . donc données j à j+2
Bon, j'ai supprimé l'entrée dans l'intégration et j'ai recréé une nouvelle entrée. ca à l'air de fonctionner.
Je sais pas ce qu'il s'est passé. Peut etre la derniere mise à jour de l'intégration
